### ISSUE TITLE
Error uploading SARIF to code scanning

### ISSUE THREAD

**Issue by CallMeGreg** [microsoft/ApplicationInspector-Action#14]
After the recent SARIF format fixes it looks like the GitHub code scanning API is unable to parse the JSON body that's sent across. With [this workflow](https://github.com/callmegreg-demo-org/demo-repo/blob/main/.github/workflows/App-Inspector.yml) I'm seeing the following error:
![Screenshot 2023-06-26 at 11 53 31 AM](https://github.com/microsoft/ApplicationInspector-Action/assets/110078080/0989ab72-af15-4c6a-b7d8-b119b9b8d41c)

From VS Code, it appears there may be an issue with the schema URL, which could be causing the issue:
<img width="1169" alt="Screenshot 2023-06-26 at 11 54 10 AM" src="https://github.com/microsoft/ApplicationInspector-Action/assets/110078080/fe76e2a9-83e3-43e0-b966-53fab676e876">

cc: @gfs @cqueern

**Comment by gfs** [comment]
Thanks @CallMeGreg. I had to create a workaround for this in DevSkim. I should be able to port it over today.
