### ISSUE TITLE
Argument add suggestions

### ISSUE THREAD

**Issue by guyacosta** [microsoft/ApplicationInspector-Action#2]
1. As a Github action I would think the -t argument to only output tags might be valuable as opposed to the verbose default for each of the format types.

2. Additionally, the exclusion filter argument will be limiting if not added as some teams have indicated the need to add/substract files or paths to scan.

**Comment by gfs** [comment]
Fixed 1. with documentation on passing simple parameters (specifically this one).  The arguments should be documented somewhere as well.  Is there a link I can point to with all of the Cli arguments?

Fixed 2 with a special parameter for the ignore path.
